app = "faselunar"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[build]
  builder = "paketobuildpacks/builder-jammy-base"
  buildpacks = ["ghcr.io/paketo-buildpacks/apt", "gcr.io/paketo-buildpacks/ruby"]

[deploy]
  release_command = "bundle exec rails db:migrate"
