# fly.toml app configuration file generated for faselua on 2023-05-18T01:28:25-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "faselua"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
  
[build]
  builder = "paketobuildpacks/builder-jammy-base"
  buildpacks = [
    "paketo-buildpacks/ruby",
    "paketo-buildpacks/node-engine",
    "paketo-buildpacks/yarn-install"
  ]
